---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "hostvars[inventory_hostname]['dhcpd_install_package'] is defined"
  - "hostvars[inventory_hostname]['dhcpd_install_package'] == 'true'"
- include: apparmor.yml
  when:
  - "hostvars[inventory_hostname]['dhcpd_configure_apparmor'] is defined"
  - "hostvars[inventory_hostname]['dhcpd_configure_apparmor'] == 'true'"
- include: deploy_dhcpd.yml
