---
- name: Enable apparmor
  service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_apparmor_service'] }}"
    enabled: "yes"
  when:
  - "dhcpd_deploy_result|success and hostvars[inventory_hostname]['dhcpd_apparmor_enable'] == 'true'"
- name: Restart apparmor
  service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_apparmor_service'] }}"
    state: "restarted"
  when:
  - "dhcpd_deploy_result|success and hostvars[inventory_hostname]['dhcpd_apparmor_restart'] == 'true'"
- name: Enable dhcpd
  service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_dhcpd_service'] }}"
    enabled: "yes"
  when:
  - "dhcpd_deploy_result|success"
  - "hostvars[inventory_hostname]['dhcpd_service_enable'] == 'true'"
- name: Restart dhcpd
  service:
    name: "{{ hostvars[inventory_hostname]['dhcpd_dhcpd_service'] }}"
    state: "restarted"
  when:
  - "dhcpd_deploy_result|success"
  - "hostvars[inventory_hostname]['dhcpd_service_restart'] == 'true'"
